### ISSUE TITLE
default on the right flags by including the logic in setup.py

### ISSUE THREAD

**Issue by lemire** [TkTech/pysimdjson#16]
It seems that it should not be necessary for the user to provide the flags in this manner:

```
CFLAGS="-march=native -std=c++17" pip install pysimdjson
```

Violating the standard (which is just pip install pysimdjson) is not great from a usability point of view (for obvious reasons).

One can detect the platform with `platform.system()` (Windows, Darwin, and so forth), and then do compile_args.append('-std=c++17') or the like.

**Comment by honnibal** [comment]
Happy to help if you have questions or need examples on this. The distutils stuff is very poorly designed, so customising these things is surprisingly fiddly.

Here's an example that sets compilation flags depending on the compiler being used: https://github.com/explosion/thinc/blob/master/setup.py

**Comment by lemire** [comment]
Note that this should extend to `-march=native` as needed.

**Comment by TkTech** [comment]
Working on cleaning up packaging, since basic functionality is done.

@lemire https://github.com/TkTech/pysimdjson/blob/develop/simdjson/cpuid.c may be of interest to you. It provides runtime checks for AVX2 CPU & host support. No more "illegal instruction". Usage: https://github.com/TkTech/pysimdjson/blob/develop/simdjson/csimdjson.pyx#L249

**Comment by lemire** [comment]
Yes. This is nice. I have opened an issue upstream.

**Comment by TkTech** [comment]
Thanks @honnibal, your example was quite useful for dealing with #17.

**Comment by TkTech** [comment]
Pushed to master and pypi, please give it a try.
