### ISSUE TITLE
The Python overhead is about 95% of the processing time

### ISSUE THREAD

**Issue by lemire** [TkTech/pysimdjson#22]
From `simdjson/scripts/javascript`, I generated a file called `large.json`. In C++, parsing this file takes about 0.25 s.

```
$parse large.json
Min:  0.252188 bytes read: 203130424 Gigabytes/second: 0.805471
```

I wrote the following Python script...

```
from timeit import default_timer as timer
with open('large.json', 'rb') as fin:
   x = fin.read()

for i in range(10):
   start = timer()
   doc = simdjson.loads(x)
   end = timer()
   print(end - start)
```

I get...

```
$ time python3 test.py
3.471898762974888
3.9210079659242183
3.3614078611135483
3.72252986789681
3.7506914171390235
3.756883286871016
3.752689895918593
3.751842977013439
3.7484844669234008
(...)
```

If my analysis is correct (and it could be wrong), pysimdjson takes 3.7 s to parse the file, and of that, 0.25 s are due to simdjson, leaving about 95% of the processing time to overhead.

I know that this is known, but I wanted to provide a data point.

**Comment by TkTech** [comment]
My benchmarks compare against json, ujson and python-rapidjson. Everything is an improvement on `json`, and the rest are all in the same ballpark for timings. It seems regardless of how fast the parser is the python object overhead is universal and consistently the majority of the time. I haven't found any particularly clever ways of speeding up object creation. We have filtering with `items()` to avoid creation in the first place, and the next step will be deferral (fake lists and objects/dicts that get replaced with a real one when called for the first time).

(p.s take a look at the `timeit` module in the stdlib for quick benchmarks)

**Comment by lemire** [comment]
Thanks. I am not surprised. It is actually a very interesting result.

**Comment by lemire** [comment]
Any chance that a trampoline approach could work? That is, leave the C++ data in an object and bring it over to Python only when requested?

**Comment by TkTech** [comment]
We need to create special dicts and lists that mimic the high-level objects, we can't just proxy since most operations would cause full materialization. It's currently beyond the effort I want to put into it with my schedule.

It's seems pretty clear there are easier gains to be made first before we go down that path. Except for the cases where it's 99% strings we're actually often slower than ujson when doing a full `loads()`. Clearly there's an improvement to be made in our bridge, since we should *never* be slower than ujson under any case.

| File | `json` time | `pysimdjson` time | `ujson` time |
| ---- | ----------- | ----------------- | ------------ |
| `jsonexamples/apache_builds.json` | 0.09162371700000001 | 0.071793139 | 0.07755472999999999 |
| `jsonexamples/canada.json` | 7.42428434 | 1.6725898010000009 | 1.6031437189999984 |
| `jsonexamples/citm_catalog.json` | 1.5878257770000008 | 1.0993508629999997 | 0.9885612419999994 |
| `jsonexamples/github_events.json` | 0.048461097000000564 | 0.03195745899999913 | 0.03887349699999909 |
| `jsonexamples/gsoc-2018.json` | 1.4824542680000015 | 0.9664357779999975 | 1.3811514339999995 |
| `jsonexamples/instruments.json` | 0.2450305869999987 | 0.1304512769999988 | 0.12935074600000007 |
| `jsonexamples/marine_ik.json` | 5.928258719000002 | 2.9537739000000016 | 2.5814395479999988 |
| `jsonexamples/mesh.json` | 1.3195111290000021 | 0.4131900339999959 | 0.37369137299999977 |
| `jsonexamples/mesh.pretty.json` | 1.9681727870000003 | 0.5725177180000003 | 0.48455140299999755 |
| `jsonexamples/numbers.json` | 0.2140409750000032 | 0.04405158500000539 | 0.05404819900000035 |
| `jsonexamples/random.json` | 0.6794662410000001 | 0.6104062659999983 | 0.5161458580000016 |
| `jsonexamples/twitter.json` | 0.522043895000003 | 0.41187920400000166 | 0.3761585310000015 |
| `jsonexamples/twitterescaped.json` | 0.7483041059999991 | 0.4323919820000057 | 0.4040483459999962 |
| `jsonexamples/update-center.json` | 0.534210778000002 | 0.4810129560000007 | 0.4786976600000017 |

**Comment by lemire** [comment]
> We need to create special dicts and lists that mimic the high-level objects, we can't just proxy since most operations would cause full materialization. It's currently beyond the effort I want to put into it with my schedule.

Ok. That seem doable.

I realize that you are pretty much the sole author of `pysimdjson`, but I think it is worthwhile to discuss and document alternative designs as other people might be able to deliver on them even if you don't have time.


> Cython was fantastic for prototyping, but I'll likely be rewriting it in plain C using the CPython C-API directly as it's at the point where I need explicit control.

Ok. That's an helpful direction.

**Comment by TkTech** [comment]
30% improvement in performance so far

**Comment by lemire** [comment]
@TkTech 30% improvement because of ...?

**Comment by TkTech** [comment]
> Cython was fantastic for prototyping, but I'll likely be rewriting it in plain C using the CPython C-API directly as it's at the point where I need explicit control.

**Comment by lemire** [comment]
@TkTech Oh. You mean secret work that you are doing in an underground lab near the capital?

I was browsing the commits. :-)

**Comment by lemire** [comment]
(This was meant as a joke.)

**Comment by TkTech** [comment]
It's been awhile since I've done proper work in C, currently hiding my shame until I can run over it a few times :)

**Comment by kootenpv** [comment]
@TkTech I came to look at the issues again, and I think the most important feature of the rewrite could actually be that it will be easier to install?

I want to depend on `pysimdjson`, but I cannot if it won't be easily installable from pypi...

**Comment by TkTech** [comment]
@kootenpv that isn't a problem of this package or the rewrite of pysimdjson's binding layer. pysimdjson has no odd dependencies preventing pip installation, and binary packages are available on pip.

simdjson uses c++17 features, and requires specific processor features. pysimdjson can't fix that.

**Comment by lemire** [comment]
@TkTech @kootenpv 

It is hard to make "installation easy" if one relies on compiling the source code each time. For one thing, not every machine can be expected to have a C++ compiler. 

That's why we usually try to deploy prebuilt binaries as much as possible. Isn't it true that this project is now widely availabe in easy-to-install binary form?

**Comment by kootenpv** [comment]
@lemire @TkTech My apologies for being dense about this. Very glad to see there are binaries available! I'll depend on `pysimdjson` then.

**Comment by TkTech** [comment]
@lemire not always possible, for example the windows binaries need to be built with the same compiler as the interpreter to be widely ABI compatible (this is fixed in recent pythons). This is why we only have win 3.6 and 3.7 binaries available for Windows, since all other versions use a compiler without C++17. C++17 really does make portability an issue.

**Comment by lemire** [comment]
I realize this but you probably don't want to support Python 2 under Windows in any case. It is really unpleasant to build code with an ancient version of Visual Studio that you would not other use.

**Comment by lemire** [comment]
In a related project, lazy parsing is used with apparently good results... 

https://github.com/luizperes/simdjson_nodejs/issues/5

**Comment by TkTech** [comment]
We already have lazy parsing with our query selectors when using `ParsedJson()` directly. Doing it for the entire document is still a placebo, and *adds* time when the entire document needs to be visited.

**Comment by ofek** [comment]
Any progress on this?

**Comment by ofek** [comment]
Fixed?

**Comment by TkTech** [comment]
There is no way to avoid the overhead of creating Python objects other than to simply not create them. This is a constant-time problem that all python JSON libraries have.

See https://github.com/TkTech/pysimdjson#making-things-faster for ways of avoiding object creation.

**Comment by lemire** [comment]
> Fixed?

I think @TkTech's answer is too complicated. I would say "YES". :-)

**Comment by ofek** [comment]
Got it, thank you!!!
