### ISSUE TITLE
Warning! diff in json and simdjson with big number

### ISSUE THREAD

**Issue by lishoujun** [TkTech/pysimdjson#37]
First: sorry for my poor English, hope you can understand my code.
pysimdjson is an awesome project, but when I handle my dataset,I found it‘s different from python json.
```
import json
import simdjson
a = b'{"acase":10699247336865531002}\n'
print(a)
b = json.loads(a)
print(b)
c= simdjson.ParsedJson(a)
print(c)
```

```
---------------------------------------------------------------------------
JSONDecodeError                           Traceback (most recent call last)
<ipython-input-4-6ab3abe7b6ca> in <module>
      5 b = json.loads(a)
      6 print(b)
----> 7 c= simdjson.ParsedJson(a)
      8 print(c)

simdjson/csimdjson.pyx in simdjson.csimdjson.ParsedJson.__init__()

JSONDecodeError: Error parsing document: line 1 column 1 (char 0)
```

**Comment by lemire** [comment]
The JSON specification recommends limiting values to binary64:

> This specification allows implementations to set limits on the range
   and precision of numbers accepted.  Since software that implements
   IEEE 754-2008 binary64 (double precision) numbers [IEEE754] is
   generally available and widely used, good interoperability can be
   achieved by implementations that expect no more precision or range
   than these provide, in the sense that implementations will
   approximate JSON numbers within the expected precision.  A JSON
   number such as 1E400 or 3.141592653589793238462643383279 may indicate
   potential interoperability problems, since it suggests that the
   software that created it expects receiving software to have greater
   capabilities for numeric magnitude and precision than is widely
   available.



The number (10699247336865531002)  in question does not fit in a 64-bit range. Among other things, it cannot be represented as a normal number in JavaScript:

<img width="414" alt="Screen Shot 2020-05-19 at 9 43 51 AM" src="https://user-images.githubusercontent.com/391987/82333896-4ab92780-99b5-11ea-83ad-e9f6d84e9456.png">

Note how silently, JavaScript will transform the value for you.

The title of your issue refers to a "diff" (difference?). There should be no difference. The simdjson library will simply refuse to parse a number that it cannot represent in the 64-bit range.

This reflects the fact that most mainstream programming languages limit their number values to, at most, a single 64-bit word.

To support arbitrary large integers, a more portable alternative would to wrap them in a string: 
<img width="441" alt="Screen Shot 2020-05-19 at 9 46 26 AM" src="https://user-images.githubusercontent.com/391987/82334193-a5eb1a00-99b5-11ea-8236-e0e82a19582a.png">



cc @jkeiser

**Comment by TkTech** [comment]
See:
- https://github.com/simdjson/simdjson/issues/560
- https://github.com/simdjson/simdjson/issues/489
- https://github.com/simdjson/simdjson/issues/425

**Comment by jkeiser** [comment]
So this is a request for > 64-bit integer support?

**Comment by TkTech** [comment]
The 3 existing issues I linked cover every possible case for supporting this. Providing a hook for number parsing would let us go from a number as a string to Python's arbitrary precision type easily. Or a flag to store it as a string with a different tag (TAG_STRING_NUM?).

Supporting arbitrary precision in simdjson itself I would not recommend, because it's almost guaranteed to be incompatible with how it's implemented in language X. We'd go from string -> simdjson arbitrary precision type -> string -> Python/Ruby/Go/C# whatever.

**Comment by lishoujun** [comment]
@lemire   Thanks for your patient reply. I learn a lot.

the difference in title I mean python’s json and pysimdjson, as show in my code, json.loads is just fine.
import json
a = b'{"acase":10699247336865531002}\n'
b = json.loads(a)

After read the specification,I knew my data is  the problem,but the data was receive form other system I can't change it to string. So I think for now I can only use python's json or ujson.
