### ISSUE TITLE
Windows 3.6 Binary?

### ISSUE THREAD

**Issue by william-silversmith** [TkTech/pysimdjson#78]
Hi! Thanks again for this fantastic project. ^_^

I ran into some CI errors where my Windows 64-bit builds were dying due to compile errors with CPython 3.6. I noticed there's no wheel on PyPI for it. 

Would it be possible to fix?

Thanks!

**Comment by TkTech** [comment]
On Windows, portable binary extensions need to be built with the same compiler version as the interpreter. We explicitly excluded Windows 3.6 from release (see https://github.com/TkTech/pysimdjson/blob/master/.github/workflows/release.yml#L23) because it used a version of msvc that didn't meet the minimum requirements for simdjson.

It now looks like recent patch versions >=3.5 use msvc 14.x, which would be acceptable. We'll need to query the CPython download stats and see how common it is, as well as check to see if the version included in the docker image we use has been rebuilt with the newer compiler.

**Comment by lemire** [comment]
Python 3.6 is in its last year and will no longer receive security updates as of the end of the year. Python 3.6 users should consider updating.

I personally found that 3.9 (released last year) had some nice performance improvements.

**Comment by TkTech** [comment]
> Python 3.6 is in its last year and will no longer receive security updates as of the end of the year. Python 3.6 users should consider updating.

While I agree totally, if we can support 3.6 with minimal pain we'll do it. We still have a fair number of users on 3.6, likely because it's the default in some LTS distributions.

Unfortunately our package usage statistics have become a bit useless as of the 23rd, since it appears someone with either a very aggressive CI or a very busy team is downloading pysimdjson several thousand times a day for version 3.7 and 3.8. Each day it's now downloaded more times than the previous 30 combined.

**Comment by lemire** [comment]
> Each day it's now downloaded more times than the previous 30 combined.

That seems like steep exponential curve that might blow up the Internet. :-)

**Comment by TkTech** [comment]
@william-silversmith You should be good to go with versions >= 4.0.0.

**Comment by william-silversmith** [comment]
Thank you so much!
